[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.8.0", features = ["bot-poise"] }
anyhow = "1.0.68"
shuttle-secrets = "0.8.0"
tracing = "0.1.37"
poise = "0.5.2"

[patch.crates-io]
shuttle-service = { path = "/home/anafabula/Disks/BtrLData/Git/ext/shuttle/service" }
